### model
model_name_or_path: /mnt/workspace/xiaoxi/model_pretrained/qwen_lab/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: VoCoT_qwen2vl_grounding  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 2048
max_samples: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/workspace/xiaoxi/xiaoxi-all/model_logs/vllm_factory/qwen2_vl-7b/lora/sft_vocot_grounding
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
run_name: vocot_grounding
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

# ### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500


# run
# llamafactory-cli train /mnt/workspace/xiaoxi/code/LLaMA-Factory/examples/train_lora/qwen2vl_lora_sft.yaml